name: Dart CI	

on:	
  push:	
    branches: [ master ]	
  pull_request:	
    branches: [ master ]	

jobs:	
  build:	

    runs-on: ubuntu-latest	

    steps:	
    - uses: actions/checkout@v1	
    - uses: subosito/flutter-action@v1	
      with:	
        channel: 'dev'	
    - run: flutter pub get
    - run: cd /opt/hostedtoolcache/flutter/1.21.0-1.0.pre-dev/x64/packages/flutter_tools && flutter pub get
    - run: sudo apt-get install -y ninja-build libgtk-3-dev && cd tests_project && flutter pub get && flutter config --enable-linux-desktop && flutter build linux --debug --verbose
    - run: flutter test
